package edu.neu.husky.wenl.huang.server.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

@DynamoDBTable(tableName="lift_records")
public class LiftRecord implements Serializable, Comparable<LiftRecord> {
    private String recordId;  // partition key for lift_records table
    private int resortId;
    private int day;
    private int skierId;
    private int liftId;
    private int time;

    public LiftRecord() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public int getResortId() {
        return resortId;
    }

    public void setResortId(int resortId) {
        this.resortId = resortId;
    }

    public int getDay() {
        return day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public int getSkierId() {
        return skierId;
    }

    public void setSkierId(int skierId) {
        this.skierId = skierId;
    }

    public int getLiftId() {
        return liftId;
    }

    public void setLiftId(int liftId) {
        this.liftId = liftId;
    }

    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }

    public int compareTo(LiftRecord that) {
        return this.time - that.getTime();
    }

    @Override
    public String toString() {
        return "LiftRecord{" + "resortId=" + resortId + ", day=" + day + ", " +
               "skierId=" + skierId + ", liftId=" + liftId + ", time=" + time + '}';
    }
}
